services:
  gpio:
    image: ${DOCKER_USER:-becktkh}/rp-gpio:${TAG:-latest}
    container_name: rp-gpio
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://127.0.0.1:5000
    ports:
      - "${PORT:-8090}:3000"
